DESIGN=Igloo2_TFT_Video_Out_Test_top
DESDIR=/home/nick/src/Igloo2_TFT_Video_Out_test/designer/Igloo2_TFT_Video_Out_Test_top
TARGET_DIR=/home/nick/src/Igloo2_TFT_Video_Out_test/designer/Igloo2_TFT_Video_Out_Test_top
FAM=IGLOO2
DIE=PA4MGL1000
PACKAGE=fg484
PINRPT_BY_NAME=1
PINRPT_BY_NUMBER=1
